<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite skipped="0" hostname="EN911042" name="uiTests.HomePageTests" tests="4" failures="1" timestamp="2020-10-07T17:21:36 COT" time="164.864" errors="0">
  <testcase name="validateLogin" time="44.359" classname="uiTests.HomePageTests"/>
  <system-out/>
  <testcase name="validateHomePage" time="50.845" classname="uiTests.HomePageTests"/>
  <system-out/>
  <testcase name="validatePersonalProject" time="48.793" classname="uiTests.HomePageTests"/>
  <system-out/>
  <testcase name="validateScreenShotError" time="20.867" classname="uiTests.HomePageTests">
    <failure type="java.lang.AssertionError" message="expected [Log Out] but found [Log In]">
      <![CDATA[java.lang.AssertionError: expected [Log Out] but found [Log In]
at org.testng.Assert.fail(Assert.java:97)
at org.testng.Assert.assertEqualsImpl(Assert.java:136)
at org.testng.Assert.assertEquals(Assert.java:118)
at org.testng.Assert.assertEquals(Assert.java:575)
at org.testng.Assert.assertEquals(Assert.java:585)
at uiTests.HomePageTests.validateScreenShotError(HomePageTests.java:38)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:134)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:597)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:173)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:816)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
at java.lang.Thread.run(Thread.java:748)
]]>
    </failure>
  </testcase> <!-- validateScreenShotError -->
  <system-out/>
</testsuite> <!-- uiTests.HomePageTests -->
