<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite hostname="EN911042" ignored="0" name="HomePageTest" tests="4" failures="1" timestamp="2020-10-07T17:18:44 COT" time="164.999" errors="0">
  <testcase name="validateLogin" time="23.36" classname="uiTests.HomePageTests"/>
  <testcase name="validateHomePage" time="22.423" classname="uiTests.HomePageTests"/>
  <testcase name="validatePersonalProject" time="28.002" classname="uiTests.HomePageTests"/>
  <testcase name="validateScreenShotError" time="0.186" classname="uiTests.HomePageTests">
    <failure type="java.lang.AssertionError" message="expected [Log Out] but found [Log In]">
      <![CDATA[java.lang.AssertionError: expected [Log Out] but found [Log In]
at uiTests.HomePageTests.validateScreenShotError(HomePageTests.java:38)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
at java.lang.Thread.run(Thread.java:748)
... Removed 17 stack frames]]>
    </failure>
  </testcase> <!-- validateScreenShotError -->
</testsuite> <!-- HomePageTest -->
